#!/bin/bash
# Calendar.app tool

CMD="$1"

case "$CMD" in
  list)
    osascript -e 'tell application "Calendar"
      set today to current date
      set todayStart to today - (time of today)
      set todayEnd to todayStart + 86400
      set output to ""
      repeat with c in calendars
        repeat with e in (every event of c whose start date >= todayStart and start date < todayEnd)
          set output to output & (start date of e) & " | " & (summary of e) & " | " & (name of c) & linefeed
        end repeat
      end repeat
      return output
    end tell'
    ;;

  add)
    TITLE="$2"
    START="$3"
    END="$4"
    NOTES="${5:-}

-- Generated by agent."

    if [ -z "$TITLE" ] || [ -z "$START" ] || [ -z "$END" ]; then
      echo "Error: Missing required arguments" >&2
      echo "Usage: ical.sh add <title> <start> <end> [notes]" >&2
      echo "Date formats: \"2026-01-05 14:00\", \"today 14:00\", \"tomorrow 15:30\"" >&2
      exit 1
    fi

    parse_date() {
      local INPUT="$1"
      local TODAY=$(date +%Y-%m-%d)
      local TOMORROW=$(date -v+1d +%Y-%m-%d)
      if [[ "$INPUT" == today* ]]; then INPUT="${INPUT/today/$TODAY}"
      elif [[ "$INPUT" == tomorrow* ]]; then INPUT="${INPUT/tomorrow/$TOMORROW}"; fi
      if [[ ! "$INPUT" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{1,2}:[0-9]{2}$ ]]; then
        echo "Error: Invalid date format '$1'" >&2
        return 1
      fi
      echo "$INPUT"
    }

    START=$(parse_date "$START") || exit 1
    END=$(parse_date "$END") || exit 1

    S_YEAR=$(echo "$START" | cut -d'-' -f1)
    S_MONTH=$(echo "$START" | cut -d'-' -f2)
    S_DAY=$(echo "$START" | cut -d' ' -f1 | cut -d'-' -f3)
    S_HOUR=$(echo "$START" | cut -d' ' -f2 | cut -d':' -f1)
    S_MIN=$(echo "$START" | cut -d':' -f2)
    E_YEAR=$(echo "$END" | cut -d'-' -f1)
    E_MONTH=$(echo "$END" | cut -d'-' -f2)
    E_DAY=$(echo "$END" | cut -d' ' -f1 | cut -d'-' -f3)
    E_HOUR=$(echo "$END" | cut -d' ' -f2 | cut -d':' -f1)
    E_MIN=$(echo "$END" | cut -d':' -f2)

    osascript -e "tell application \"Calendar\"
      set agentCal to first calendar whose name is \"Agent\"
      set startDate to current date
      set year of startDate to $S_YEAR
      set month of startDate to $S_MONTH
      set day of startDate to $S_DAY
      set hours of startDate to $S_HOUR
      set minutes of startDate to $S_MIN
      set seconds of startDate to 0
      set endDate to current date
      set year of endDate to $E_YEAR
      set month of endDate to $E_MONTH
      set day of endDate to $E_DAY
      set hours of endDate to $E_HOUR
      set minutes of endDate to $E_MIN
      set seconds of endDate to 0
      set props to {summary:\"$TITLE\", start date:startDate, end date:endDate, description:\"$NOTES\"}
      make new event at end of events of agentCal with properties props
      return \"Event created: $TITLE\"
    end tell"
    ;;

  calendars)
    osascript -e 'tell application "Calendar"
      set output to ""
      repeat with c in calendars
        set output to output & (name of c) & linefeed
      end repeat
      return output
    end tell'
    ;;

  ensure)
    osascript -e 'tell application "Calendar"
      set calNames to name of every calendar
      if "Agent" is not in calNames then
        make new calendar with properties {name:"Agent"}
        return "Created Agent calendar"
      else
        return "Agent calendar exists"
      end if
    end tell'
    ;;

  *)
    echo "Usage: ical.sh <list|add|calendars|ensure>" >&2
    exit 1
    ;;
esac
